//
//  PrivacyPolicyView.swift
//  Ignition Mobile Tracker
//
//  Created by SASU TALHA Dev Team on 06/10/25.
//

import SwiftUI

struct PrivacyPolicyView: View {
    @StateObject private var themeManager = ThemeManager.shared
    
    var body: some View {
        ScrollView {
            VStack(alignment: .leading, spacing: IgnitionSpacing.lg) {
                // Header
                VStack(alignment: .leading, spacing: IgnitionSpacing.sm) {
                    Text("Privacy Policy")
                        .font(.largeTitle)
                        .fontWeight(.bold)
                        .foregroundColor(themeManager.primaryTextColor)
                    
                    Text("Ignition Mobile Tracker")
                        .font(.title3)
                        .foregroundColor(themeManager.secondaryTextColor)
                    
                    Text("Last updated: October 2025")
                        .font(.caption)
                        .foregroundColor(themeManager.secondaryTextColor)
                }
                .padding(.bottom, IgnitionSpacing.md)
                
                Divider()
                
                // Introduction
                PolicySection(
                    title: "1. Introduction",
                    content: "Welcome to Ignition Mobile Tracker, a mobile application (\"App\") developed by SASU TALHA (\"we,\" \"our,\" or \"us\").\n\nYour privacy is important to us. This Privacy Policy describes how we collect, use, store, protect, and share (if applicable) information when you use our App, in compliance with the General Data Protection Regulation (GDPR), California Consumer Privacy Act (CCPA), and other applicable data protection laws.\n\nBy downloading, installing, or using Ignition Mobile Tracker, you consent to the collection and use of information as described in this Privacy Policy."
                )
                
                // Data Controller
                PolicySection(
                    title: "2. Data Controller and Contact",
                    content: "SASU TALHA\nEmail: a.ucan@sasutalha.fr\n\nRegistered in France\nResponsible for the processing of data collected via Ignition Mobile Tracker.\n\nFor any questions about this Privacy Policy or to exercise your data rights, please contact us at the email address above."
                )
                
                // What Data We Collect
                PolicySection(
                    title: "3. What Data We Collect",
                    content: """
                    3.1. Information You Provide Voluntarily
                    
                    We may collect information that you voluntarily provide within the App, including:
                    • Name or nickname, if entered in the profile section
                    • Optional notes or reflections, entered by the user in trackers or logs
                    • Custom tags or categories, used to organize tracked data
                    
                    This data is stored locally on your device and is never uploaded to external servers.
                    
                    3.2. Automatically Collected Information
                    
                    We may collect non-personal, technical data automatically generated by your device, including:
                    • Device model and operating system version
                    • App version
                    • Diagnostic data such as crash logs or performance statistics
                    • Anonymous analytics (if enabled through Apple frameworks)
                    
                    These data are aggregated and anonymized and do not identify any individual.
                    
                    3.3. No Sensitive Data
                    
                    The app does not collect or process any sensitive personal information such as:
                    • Financial or payment data
                    • Biometric identifiers
                    • Location (GPS) data
                    • Contacts, camera, or microphone input
                    • Health or medical information
                    
                    The app functions entirely offline and does not require an account or login.
                    """
                )
                
                // Purpose
                PolicySection(
                    title: "4. Purpose of Data Processing",
                    content: """
                    We collect and process data strictly for the following purposes:
                    
                    • App Functionality — To save your tracked data, activities, and progress
                    • Improvement of User Experience — To optimize usability and performance
                    • Diagnostics and Bug Fixing — To identify and resolve crashes or app errors
                    • User Communication (Optional) — To respond to your privacy or support inquiries sent via email
                    
                    We will never sell, rent, or monetize your information.
                    """
                )
                
                // Legal Basis
                PolicySection(
                    title: "5. Legal Basis for Processing (GDPR)",
                    content: """
                    For users located in the European Economic Area (EEA), the processing of personal data is based on one or more of the following legal bases:
                    
                    • Performance of a contract: to provide the App and its core features
                    • Consent: for any optional features or manual data entry
                    • Legitimate interest: to ensure security, app integrity, and continuous improvement
                    
                    Users can withdraw consent at any time by deleting their data or uninstalling the App.
                    """
                )
                
                // Storage
                PolicySection(
                    title: "6. Data Storage and Retention",
                    content: """
                    • All tracked and user-generated data are stored only locally on your device
                    • We do not transfer or back up your information to cloud services or remote servers
                    • If you delete the App, all associated data are permanently removed
                    • Diagnostic or performance data (if any) retained by Apple are managed according to Apple's privacy policies
                    • We retain no external copies of your data
                    """
                )
                
                // Security
                PolicySection(
                    title: "7. Data Security",
                    content: """
                    We employ multiple layers of protection to ensure data integrity:
                    
                    • Local storage within the iOS secure sandbox environment
                    • Encryption through device-level security (e.g., Apple Data Protection APIs)
                    • No external data transmission without explicit user consent
                    
                    Users are encouraged to protect their device with a passcode or biometric lock.
                    """
                )
                
                // Sharing
                PolicySection(
                    title: "8. Data Sharing and Third Parties",
                    content: """
                    Ignition Mobile Tracker does not share personal data with third parties.
                    However, the App may integrate certain system-level frameworks provided by Apple (for example, system diagnostics). These operate under Apple's privacy policies, and all data handled through them are anonymized.
                    
                    We do not use:
                    • Advertising SDKs
                    • Analytics trackers that identify users
                    • Third-party cloud storage
                    """
                )
                
                // Rights
                PolicySection(
                    title: "9. Your Data Protection Rights",
                    content: """
                    Under GDPR (EU/EEA Users):
                    • Right of Access: Request a copy of the personal data we hold
                    • Right to Rectification: Correct inaccurate or incomplete data
                    • Right to Erasure ("Right to be Forgotten"): Delete your local data or uninstall the app
                    • Right to Restriction: Limit the use of your data in specific cases
                    • Right to Portability: Receive your data in a machine-readable format (if technically feasible)
                    • Right to Object: Object to certain types of processing (e.g., analytics)
                    • Right to Lodge a Complaint: File a complaint with your national data protection authority
                    
                    Under CCPA (California, USA):
                    • Right to Know: Request information about what data are collected and how they are used
                    • Right to Delete: Request deletion of your data (handled locally)
                    • Right to Opt-Out of Sale: We do not sell or trade user data
                    • Right to Non-Discrimination: You will not be penalized for exercising your privacy rights
                    
                    To exercise any of these rights, please contact us at a.ucan@sasutalha.fr
                    """
                )
                
                // Children
                PolicySection(
                    title: "10. Children's Privacy",
                    content: "Our App is not intended for children under 13 years of age (or under 16 in some EU countries). We do not knowingly collect or store information from minors. If we become aware that a child has submitted personal information, we will delete it immediately upon notice."
                )
                
                // Summary
                VStack(alignment: .leading, spacing: IgnitionSpacing.md) {
                    Text("Summary")
                        .font(.title2)
                        .fontWeight(.bold)
                        .foregroundColor(themeManager.primaryTextColor)
                    
                    VStack(alignment: .leading, spacing: IgnitionSpacing.sm) {
                        SummaryPoint(text: "Your data stay offline and on your device only")
                        SummaryPoint(text: "We never share, sell, or track your personal information")
                        SummaryPoint(text: "You can delete all data at any time by removing the App")
                        SummaryPoint(text: "We fully comply with EU GDPR, CCPA, and Apple developer policies")
                    }
                }
                .padding(.vertical, IgnitionSpacing.md)
                .padding(.horizontal, IgnitionSpacing.md)
                .background(themeManager.primaryColor.opacity(0.1))
                .cornerRadius(IgnitionCornerRadius.lg)
                
                // Contact
                PolicySection(
                    title: "Contact Information",
                    content: """
                    For privacy-related questions or requests, you can reach us at:
                    
                    SASU TALHA
                    Email: a.ucan@sasutalha.fr
                    Country: France
                    
                    We aim to respond to all privacy-related inquiries within 30 days.
                    """
                )
            }
            .padding(IgnitionSpacing.lg)
        }
        .background(themeManager.backgroundColor)
        .navigationTitle("Privacy Policy")
        .navigationBarTitleDisplayMode(.inline)
    }
}

struct PolicySection: View {
    @StateObject private var themeManager = ThemeManager.shared
    let title: String
    let content: String
    
    var body: some View {
        VStack(alignment: .leading, spacing: IgnitionSpacing.sm) {
            Text(title)
                .font(.title3)
                .fontWeight(.semibold)
                .foregroundColor(themeManager.primaryTextColor)
            
            Text(content)
                .font(.body)
                .foregroundColor(themeManager.secondaryTextColor)
                .fixedSize(horizontal: false, vertical: true)
        }
        .padding(.bottom, IgnitionSpacing.md)
    }
}

struct SummaryPoint: View {
    @StateObject private var themeManager = ThemeManager.shared
    let text: String
    
    var body: some View {
        HStack(alignment: .top, spacing: IgnitionSpacing.sm) {
            Image(systemName: "checkmark.circle.fill")
                .foregroundColor(themeManager.primaryColor)
                .font(.body)
            
            Text(text)
                .font(.body)
                .foregroundColor(themeManager.primaryTextColor)
        }
    }
}

#Preview {
    NavigationStack {
        PrivacyPolicyView()
    }
}
